version: "3"
services:
  test:
    build: .
    ports:
      - "4100"
    container_name: vocabulary-tag-test
    environment:
      PORT: 4100
      NODE_ENV: test
      GATEWAY_URL: http://mymachine:9000
      MONGO_PORT_27017_TCP_ADDR: mongo
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    ports:
      - "27017"
