apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vocabulary
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: vocabulary
  minReplicas: 5
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50
